---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traefikcertwatchers.arola.local
spec:
  scope: Namespaced
  group: arola.local
  names:
    kind: TraefikCertWatcher
    plural: traefikcertwatchers
    singular: traefikcertwatcher
    shortNames:
      - tcw
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true